Values:
  server:
    service:
      type: LoadBalancer
  redis:
    master:
      persistence:
        storageClass: alicloud-disk-essd
        size: 40Gi
WaitUntils:
  - Kind: Service
    Name: argocd-server
    JsonPath: $.status.loadBalancer.ingress[0].ip
    Operator: NotEmpty
    FirstMatch: true
    Timeout: 300
Outputs:
  Kind: Service
  Name: argocd-server
  JsonPath: $.status.loadBalancer.ingress[0].ip
Protocol: https
port: 8080