Parameters:
  - Name: AdminPassword
    NoEcho: true
    Type: String
    Label: 管理员密码
    AssociationProperty: ALIYUN::ECS::Instance::Password
Command: echo ${AdminPassword}
Outputs:
  - Label: Endpoint
    Expression: https://${Address}:8080